version: '3.5'

services:
  lunchroom:
    image: ${DOCKER_REGISTRY-}lunchroom
    env_file: .env
    build:
      context: .
      dockerfile: LunchRoom/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DbConnection=Server=postgres;Port=5432;User Id=${DB_USER_NAME};Password=${DB_USER_PASSWORD};Database=${DB_NAME};
      - MailServer__Host=${MAIL_HOST}
      - MailServer__Port=${MAIL_PORT}
      - MailServer__ServiceAccount=${MAIL_SERVICE_ACCOUNT_NAME}
      - MailServer__Password=${MAIL_SERVICE_ACCOUNT_PASS}
      - MailServer__Sender=${MAIL_TARGET_SENDER}
      - MailServer__HostSmtp=${MAIL_HOST_SMTP}
      - MailServer__PortSmtp=${MAIL_PORT_SMTP}
      - AdminEmail=${ADMIN_EMAIL}
      - LunchRoomDomainName=${LUNCHROOM_DOMAIN_NAME}
    ports:
      - "5129:5129"
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1
    env_file: .env
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client/Dockerfile
    environment:
      - ApiUrl=http://lunchroom
      - DomainName=${DOMAIN_NAME}
    ports:
      - "5097:80"
    depends_on:
      - postgres
      - lunchroom
  